---
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "/vector-{{ vector_version }}.tar.gz"
  register: download_vector

- name: Create directory for Vector
  ansible.builtin.file:
    state: directory
    path: "{{ vector_home }}"

# not indempotent(
#- name: add repo cent 8
#  ansible.builtin.shell:
#  when:
#    - ansible_facts['distribution'] == "CentOS"
#    - ansible_facts['distribution_major_version'] == "8"

- name: extractor presents
  ansible.builtin.yum:
    name:
      - unzip
      - tar
    state: present

- name: Extract vector in directory
  ansible.builtin.unarchive:
    src: "/vector-{{ vector_version }}.tar.gz"
    dest: "{{ vector_home }}"
    extra_opts: [ --strip-components=2 ]
    remote_src: yes
  when: download_vector.changed

- name: Create a symbolic link
  ansible.builtin.file:
    src: "{{ vector_home }}/bin/vector"
    dest: "/usr/bin/vector"
    owner: root
    group: root
    state: link
  notify:
    - Check succses install vector
    - debug details